(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const title=$("#coreTitle"),subtitle=$("#coreSubtitle"),core=$("#coreButton"),prompt=$("#promptText"),setup=$("#promptSetup"),lanePill=$("#selectedLane"),depthPill=$("#selectedDepth"),copy=$("#copyPrompt"),copyStatus=$("#copyStatus");
let lane="",depth="";
function showOrb(orb){title.textContent=orb.dataset.title||"Choose";subtitle.textContent=orb.dataset.subtitle||"a testing lane"}
function resetOrb(){title.textContent="Choose";subtitle.textContent="a testing lane"}
$$(".nexus .lane-orb").forEach(orb=>{orb.addEventListener("mouseenter",()=>showOrb(orb));orb.addEventListener("focus",()=>showOrb(orb));orb.addEventListener("mouseleave",resetOrb);orb.addEventListener("blur",resetOrb)});
core.addEventListener("click",()=>core.animate([{transform:"translate(-50%,-50%) scale(1)"},{transform:"translate(-50%,-50%) scale(1.06)"},{transform:"translate(-50%,-50%) scale(1)"}],{duration:900,easing:"cubic-bezier(.2,.8,.2,1)"}));
function updatePrompt(){
lanePill.textContent="Lane: "+(lane||"not selected");depthPill.textContent="Depth: "+(depth||"not selected");
setup.textContent=lane&&depth?`${lane} lane · ${depth} test`:lane?`${lane} lane · choose a depth`:depth?`${depth} test · choose a lane`:"Choose a lane and depth above. The prompt updates automatically.";
prompt.textContent=prompt.textContent.replace(/Lane: .*/,"Lane: "+(lane||"[SELECT A LANE]")).replace(/Depth: .*/,"Depth: "+(depth||"[SELECT A TEST DEPTH]"));
}
$$("[data-lane]").forEach(button=>button.addEventListener("click",()=>{lane=button.dataset.lane;$$("[data-lane]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));updatePrompt()}));
$$("[data-depth]").forEach(button=>button.addEventListener("click",()=>{depth=button.dataset.depth;$$("[data-depth]").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));updatePrompt()}));
copy.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(prompt.innerText||prompt.textContent);copy.textContent="Copied";copyStatus.textContent="Prompt copied.";setTimeout(()=>{copy.textContent="Copy prompt";copyStatus.textContent=""},1500)}catch{copyStatus.textContent="Select and copy the prompt manually."}});

const list=$("#recordList"),empty=$("#archiveEmpty"),count=$("#archiveCount"),statusLine=$("#archiveStatus"),search=$("#recordSearch"),statusFilter=$("#statusFilter"),domainFilter=$("#domainFilter"),depthFilter=$("#depthFilter"),sortFilter=$("#sortFilter");
const state={records:[],filtered:[]},arr=v=>Array.isArray(v)?v:[],norm=v=>String(v||"").trim().toLowerCase(),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function href(v){try{const u=new URL(String(v||""),document.baseURI);return["http:","https:"].includes(u.protocol)?u.href:"#"}catch{return"#"}}
function addOptions(select,values){[...new Set(values.filter(Boolean))].sort().forEach(value=>{const o=document.createElement("option");o.value=norm(value);o.textContent=value;select.appendChild(o)})}
function recordCard(record){
const files=arr(record.downloads),tabs=[["summary","Summary"],["sources","Sources"],["methods","Methods"],["evidence","Evidence"],["notes","Notes"]],panes={summary:record.summary||record.question||"Summary pending.",sources:arr(record.source_ids).length?arr(record.source_ids).join(", "):"No public source list is attached.",methods:record.method_summary||"Method summary pending.",evidence:record.evidence_summary||"Evidence summary pending.",notes:arr(record.ambiguities).concat(arr(record.failures)).join("\n")||"No public ambiguity or failure notes are attached."},recordTitle=record.title||record.question||record.record_id||"Untitled record",id=record.record_id||"Record ID pending";
return`<details class="record-card"><summary><div><div class="record-title">${esc(recordTitle)}</div><div class="record-meta"><span class="record-pill">${esc(id)}</span><span class="record-pill">${esc(record.status||"unclassified")}</span><span class="record-pill">${esc(record.test_depth||"depth pending")}</span>${record.domain?`<span class="record-pill">${esc(record.domain)}</span>`:""}</div></div><span class="record-chevron">⌄</span></summary><div class="record-body"><div class="record-tabs" role="tablist">${tabs.map((tab,i)=>`<button type="button" role="tab" aria-selected="${i===0}" data-tab="${tab[0]}">${tab[1]}</button>`).join("")}</div>${tabs.map((tab,i)=>`<div class="record-pane" data-pane="${tab[0]}" ${i?"hidden":""}>${esc(panes[tab[0]])}</div>`).join("")}${files.length?`<div class="download-row">${files.map(file=>`<a href="${href(file.href)}">${esc(file.label||file.format||"Download")}</a>`).join("")}</div>`:""}</div></details>`}
function wireTabs(){$$(".record-card").forEach(card=>card.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>{card.querySelectorAll("[data-tab]").forEach(b=>b.setAttribute("aria-selected","false"));card.querySelectorAll("[data-pane]").forEach(p=>p.hidden=true);button.setAttribute("aria-selected","true");const pane=card.querySelector(`[data-pane="${button.dataset.tab}"]`);if(pane)pane.hidden=false})))}
function apply(){
const q=norm(search.value),st=norm(statusFilter.value),dm=norm(domainFilter.value),dp=norm(depthFilter.value),rank={light:1,medium:2,heavy:3};
state.filtered=state.records.filter(r=>{const hay=norm([r.record_id,r.title,r.question,r.summary,r.domain,arr(r.tags).join(" "),arr(r.source_ids).join(" ")].join(" "));return(!q||hay.includes(q))&&(!st||norm(r.status)===st)&&(!dm||norm(r.domain)===dm)&&(!dp||norm(r.test_depth)===dp)});
state.filtered.sort((a,b)=>{switch(sortFilter.value){case"updated-asc":return String(a.updated_at||"").localeCompare(String(b.updated_at||""));case"title-asc":return String(a.title||a.record_id||"").localeCompare(String(b.title||b.record_id||""));case"depth-asc":return(rank[norm(a.test_depth)]||9)-(rank[norm(b.test_depth)]||9);case"status-asc":return String(a.status||"").localeCompare(String(b.status||""));default:return String(b.updated_at||"").localeCompare(String(a.updated_at||""))}});
list.innerHTML=state.filtered.map(recordCard).join("");empty.hidden=state.records.length!==0;count.textContent=state.records.length?`${state.filtered.length} of ${state.records.length} records`:"No released records";statusLine.textContent=state.records.length?(state.filtered.length?"Public archive loaded":"No records match these filters"):"Public archive loaded. No records released yet.";wireTabs()}
[search,statusFilter,domainFilter,depthFilter,sortFilter].forEach(control=>control.addEventListener(control===search?"input":"change",apply));
fetch("trigon/manifest.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(manifest=>{state.records=arr(manifest.records).filter(record=>record&&record.public_release===true);addOptions(statusFilter,state.records.map(r=>r.status));addOptions(domainFilter,state.records.map(r=>r.domain));apply()}).catch(()=>{statusLine.textContent="Public archive connection unavailable.";count.textContent="";empty.hidden=true;list.innerHTML='<div class="archive-empty"><span>!</span><h3>The archive connection is unavailable.</h3><p>The Trigon page is intact, but the public manifest could not be read. Please try again later.</p></div>'});
})();